# Generated by Django 5.1.5 on 2026-09-20 05:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by', '-created_at'], name='events_even_created_fdbe6f_idx'),
        ),
        migrations.AddIndex(
            model_name='eventmember',
            index=models.Index(fields=['event', 'user'], name='events_even_event_i_ba33a4_idx'),
        ),
        migrations.AddIndex(
            model_name='eventmember',
            index=models.Index(fields=['user', 'event'], name='events_even_user_id_acaa63_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventmember',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_event_member'),
        ),
    ]
