# Generated by Django 5.1.5 on 2026-09-20 05:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_identifier', models.CharField(db_index=True, max_length=64, unique=True)),
                ('pin_hash', models.CharField(max_length=128)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='galleries.gallery')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_selections', to='photos.photo')),
            ],
        ),
        migrations.AddIndex(
            model_name='gallery',
            index=models.Index(fields=['event', 'published'], name='galleries_g_event_i_810007_idx'),
        ),
        migrations.AddConstraint(
            model_name='gallery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('published', False), ('published_at__isnull', True)), models.Q(('published', True), ('published_at__isnull', False)), _connector='OR'), name='gallery_published_timestamp_consistent'),
        ),
        migrations.AddIndex(
            model_name='galleryphoto',
            index=models.Index(fields=['gallery', 'created_at'], name='galleries_g_gallery_0ec4b6_idx'),
        ),
        migrations.AddIndex(
            model_name='galleryphoto',
            index=models.Index(fields=['photo', 'gallery'], name='galleries_g_photo_i_b84e10_idx'),
        ),
        migrations.AddConstraint(
            model_name='galleryphoto',
            constraint=models.UniqueConstraint(fields=('gallery', 'photo'), name='unique_gallery_photo'),
        ),
    ]
