# Generated by Django 5.1.5 on 2026-09-20 07:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='galleries.gallery')),
            ],
            options={
                'indexes': [models.Index(fields=['gallery', 'created_at'], name='galleries_g_gallery_4fab95_idx')],
            },
        ),
    ]
